### ISSUE TITLE
import with github.com prefix

### ISSUE THREAD

**Issue by WangFenjin** [verizonlabs/mesos-framework-sdk#18]
Hi,

I noticed that the import path in our code base is prefixed with "mesos-framework-sdk", which is not following [golang code style ](https://golang.org/doc/code.html#ImportPaths).

Could we fix this? I can submit a PR for this if you would.

**Comment by aaronjwood** [comment]
Hey there, I think that this is a good idea and would benefit the community now that we've open sourced everything. Feel free to send a PR!
